src/OdeToFood/ViewComponents/GreetingViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Services;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
    public class GreetingViewComponent : ViewComponent
    {
        private IGreeter greeter;

        public GreetingViewComponent(IGreeter greeter)
        {
            this.greeter = greeter;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            var model = this.greeter.GetGreeting();
            return Task.FromResult<IViewComponentResult>(this.View("Default", model));
        }
    }
}

src/OdeToFood/ViewComponents/LoginLogoutViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace OdeToFood.ViewComponents
{
    public class LoginLogoutViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return this.View();
        }
    }
}

src/OdeToFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <environment names="Development">
        <link href="/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    </environment>
    <environment names="Staging, Production">
        <link href="http://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"
              asp-fallback-href="/node_modules/bootstrap/dist/css/bootstrap.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">OdeToFood</a>
            </div>
            <div class="navbar-right">
                @await Component.InvokeAsync("LoginLogout")
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
        <footer>
            @RenderSection("footer", required: false)
            @await Component.InvokeAsync("Greeting")
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>